// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llguuxqvggwpqjhupnjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZ3V1eHF2Z2d3cHFqaHVwbmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTQyNTQsImV4cCI6MjA1OTc3MDI1NH0.7YJkRFBdhsRt8u-sXWgEFNbRFyhQWKsQHcF656WGHcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);