
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llguuxqvggwpqjhupnjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZ3V1eHF2Z2d3cHFqaHVwbmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTQyNTQsImV4cCI6MjA1OTc3MDI1NH0.7YJkRFBdhsRt8u-sXWgEFNbRFyhQWKsQHcF656WGHcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Extended RPC functions interface
interface RPCFunctions {
  create_supplier: (args: {
    supplier_id: string;
    company_type_id_input: number;
    company_name_input: string;
    location_input: string;
    country_input: string;
    phone_number_input: string;
    kra_pin_input: string;
    physical_address_input: string | null;
    website_url_input: string | null;
  }) => Promise<{ data: null; error: any }>;
  
  add_supplier_category: (args: {
    supplier_id_input: string;
    category_id_input: number;
  }) => Promise<{ data: null; error: any }>;
  
  add_supplier_location: (args: {
    supplier_id_input: string;
    location_id_input: number;
  }) => Promise<{ data: null; error: any }>;
}

// Extend the supabase client's rpc method to include our custom functions
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    rpc<
      FunctionName extends keyof Database['public']['Functions'] | keyof RPCFunctions
    >(
      fn: FunctionName,
      args?: FunctionName extends keyof Database['public']['Functions']
        ? Parameters<Database['public']['Functions'][FunctionName]>[0]
        : FunctionName extends keyof RPCFunctions
        ? Parameters<RPCFunctions[FunctionName]>[0]
        : never
    ): Promise<{ data: any; error: any }>;
  }
}
